### ISSUE TITLE
어떤 의미인가요?

### ISSUE THREAD

**Issue by npmachine** [odk410/baekjoon#1]
https://github.com/odk410/baekjoon/blob/25d7c68a719b95303cd4dce05f402a9d38b6409e/7568.rb#L12

이 if문이 왜 있는지 잘 이해가 가지 않네요.
N-1이면 배열의 마지막 케이스인데 마지막 케이스는 실행 안하겠다는 말인가요?

**Comment by odk410** [comment]
네 배열의 마지막은 비교를 안하기 위해서 if문을 작성했습니다.
